[package]
name = "mutants-batch"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.3"
aws-sdk-batch = "1.90.0"
aws-sdk-cloudwatch = "1.84.0"
aws-sdk-cloudwatchlogs = "1.96.0"
fastrand = "2.3.0"
time = { version = "0.3.41", features = ["formatting"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
