[package]
name = "mutants-remote"
version = "0.1.0"
edition = "2024"
publish = false        # for now

[dependencies]
aws-config = "1.8.3"
aws-sdk-batch = "1.90.0"
aws-sdk-cloudwatch = "1.84.0"
aws-sdk-cloudwatchlogs = "1.96.0"
aws-sdk-s3 = "1.100.0"
aws-sdk-sts = "1.80.0"
bytes = "1.10.1"
async-trait = "0.1"
chrono = "0.4.41"
thiserror = "1.0"
fastrand = "2.3.0"
time = { version = "0.3.41", features = ["formatting"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
clap = { version = "4.5", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["display"] }
